### ISSUE TITLE
Make CPAN package

### ISSUE THREAD

**Issue by rvosa** [rvosa/bio-phylo-forest-dbtree#7]
Steps:

- [x] create a Makefile.PL
- [x] decide on CPAN package name (see #2)
- [x] write documentation (see #5)
- [x] include CPAN-compatable unit tests (see #8) 
- [x] upload to CPAN
